### ISSUE TITLE
Exception when running example

### ISSUE THREAD

**Issue by mellowcandle** [eshaham/israeli-bank-scrapers#166]
Steps I did in order to check:
$ npm init
$ npm install israeli-bank-scrapers --save

Node version: v10.12.0

It might be trivial, but what am I missing ?

Thanks,
Ramon.

```
/home/rfried/scraper/index.js:1
(function (exports, require, module, __filename, __dirname) { import { createScraper } from 'israeli-bank-scrapers';
                                                                     ^
SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

```

**Comment by esakal** [comment]
Hi,
I'm installed it with node v10.13.0 (which is LTS) and it seems to work (see log below). 

can you try again with version v10.12.0? you can use the [npm package - n](https://www.npmjs.com/package/n) to switch between versions.


```
➜  ss npm install israeli-bank-scrapers

> puppeteer@1.9.0 install /Users/eransakal/dev/temp/ss/node_modules/puppeteer
> node install.js

Downloading Chromium r594312 - 82.7 Mb [====================] 99% 0.0s
Chromium downloaded to /Users/eransakal/dev/temp/ss/node_modules/puppeteer/.local-chromium/mac-594312
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ss@1.0.0 No description
npm WARN ss@1.0.0 No repository field.

+ israeli-bank-scrapers@0.6.4
added 53 packages from 40 contributors and audited 62 packages in 42.776s
found 0 vulnerabilities

➜  ss node -v
v10.13.0
➜  ss
```

**Comment by mellowcandle** [comment]
Hi.
I switched to node v10.13.0.
I get the same error...

**Comment by eshaham** [comment]
@mellowcandle maybe you're not using babel?
the `import { func } from 'module'` syntax is still not supported natively in node.js, AFAIK.
an easy fix would be to change your import code to
```node
const { createScraper } = require('israeli-bank-scrapers');
```

**Comment by eshaham** [comment]
@mellowcandle closing this for now
