### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by eitansela** [eshaham/israeli-bank-scrapers#257]
Steps I executed in order to reproduce:
$ npm init
$ npm install israeli-bank-scrapers --save

Node version: v12.10.0

```
const scrapeResult = await scraper.scrape(credentials);
                     ^^^^^

SyntaxError: await is only valid in async function
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

Maybe it is a begginer issue...
Help will be appriciated.

**Comment by esakal** [comment]
Hi @eitansela ,

I assume you try to run this method directly in the file/module. if so, you should wrap it with IIFE function:
```
(async function(){
try {
   const scrapeResult = await scraper.scrape(credentials);
} catch(e) 
{
   // todo handle unexpected error here
}
})();

**Comment by eitansela** [comment]
Hello @esakal, thanks for the quick response.
I followed the Getting started guide I did exatclly what was written.

I am relativly new to NodeJs/JavaScript...
Can you maybe attach source code of a working example?

**Comment by esakal** [comment]
Try the following
```
const { createScraper } = require('israeli-bank-scrapers');

const credentials = {...}; // different for each bank
const options = {...};

(async function() {
   try {
      const scraper = createScraper(options);
      const scrapeResult = await scraper.scrape(credentials);
   
      if (scrapeResult.success) {
        scrapeResult.accounts.forEach((account) => {
           console.log(`found ${account.txns.length} transactions for account number 
            ${account.accountNumber}`);
        });
      }
      else {
         throw new Error(scrapeResult.errorType);
      }
   } catch(e) {
      console.error(`scraping failed for the following reason: ${e.message}`);
   }
})();
```

let me know if it worked for you

**Comment by eitansela** [comment]
@esakal works amazing!
Thanks!
