### ISSUE TITLE
MAX card error

### ISSUE THREAD

**Issue by gczobel** [eshaham/israeli-bank-scrapers#395]
I added a new scraper for MAX card and is not working.

scraping Max
Max: START_SCRAPING
Max: INITIALIZING
Max: LOGGING_IN
Max: LOGIN_SUCCESS
Max: TERMINATING
Max: END_SCRAPING
success: false
error type: GENERIC
error: Unknown transaction type תשלום חודשי
Error: Unknown transaction type תשלום חודשי
    at exports.default (c:/ynab/israeli-ynab-updater/src/scrape/scrape-base.js:62:11)
    at exports.default (c:/ynab/israeli-ynab-updater/src/scrape/scrape-task.js:84:33)
    at exports.default (c:/ynab/israeli-ynab-updater/src/scrape/scraping-main-menu.js:30:7)
(node:1656) UnhandledPromiseRejectionWarning: Error: Unknown transaction type תשלום חודשי
    at exports.default (c:/ynab/israeli-ynab-updater/src/scrape/scrape-base.js:62:11)
    at exports.default (c:/ynab/israeli-ynab-updater/src/scrape/scrape-task.js:84:33)
    at exports.default (c:/ynab/israeli-ynab-updater/src/scrape/scraping-main-menu.js:30:7)
(node:1656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any idea?

**Comment by esakal** [comment]
Hi @gczobel we are adding txn types once we encounter them. I didn't get this one yet but the fix is quite trivial.

please pull #396, run it and let me know if it fixed your problem. If so I will merge it.

- Eran

**Comment by gczobel** [comment]
Ok, I took the code and run with the change and found another missing type.
These two are missing:
const MONTHLY_PAYMENT = 'תשלום חודשי';
const FUTURE_PURCHASE_FINANCING = 'מימון לרכישה עתידית';

**Comment by esakal** [comment]
Try now

**Comment by gczobel** [comment]
Yes. Is working now.
Thanks!
