### ISSUE TITLE
Amex scraper is broken

### ISSUE THREAD

**Issue by tpseven-777** [eshaham/israeli-bank-scrapers#539]
It seems like there're some issues with Amex scraper this morning (Israecard scraper does work)
This issue is experienced with `v.0.9.1`, `v.1.0.0` and `next`

`$ node --trace-warnings .
Starting to scrape amex...
Evaluation failed: TypeError: Failed to fetch
(node:29436) UnhandledPromiseRejectionWarning: Error: GENERIC
    at scrapeSingleCard (/home/-----/homedev/index.js:671:10)
    at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
    at processPromiseRejections (internal/process/promises.js:211:11)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(node:29436) Error: GENERIC
    at scrapeSingleCard (/home/-----/homedev/index.js:671:10)
(node:29436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:161:11)
    at processPromiseRejections (internal/process/promises.js:213:13)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
`

**Comment by tpseven-777** [comment]
It seems like this issue is now gone. I haven't done anything besides re-running, so maybe something had changed in the web site
