### ISSUE TITLE
Max scraper is broken

### ISSUE THREAD

**Issue by ifeins** [eshaham/israeli-bank-scrapers#552]
When trying to scrape Max transactions I get the following error:

```
scraping Max
Max: START_SCRAPING
Max: INITIALIZING
Max: LOGGING_IN
Max: TERMINATING
Max: END_SCRAPING
success: false
error type: TIMEOUT
error: waiting for redirect from https://www.max.co.il/homepage/welcome
Error: waiting for redirect from https://www.max.co.il/homepage/welcome
    at _default (/Users/ifeins/Development/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
(node:60147) UnhandledPromiseRejectionWarning: Error: waiting for redirect from https://www.max.co.il/homepage/welcome
    at _default (/Users/ifeins/Development/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
(node:60147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:60147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Did anyone encounter this issue?

**Comment by ifeins** [comment]
Closing as apparently there was something wrong in my configuration of the scraper.
