### ISSUE TITLE
[hapoalim] Fetch error

### ISSUE THREAD

**Issue by daniel-hauser** [eshaham/israeli-bank-scrapers#640]
# Description
The poalim scraper stops to work with a `TypeError: Failed to fetch` error.
After investigating, seems like the endpoint added in #576 redirects to itself if the account is closed- causing the error.

# Solution
A possible solution is to wrap the balance logic in a try-catch and fallback the balance to undefined (the value before the #576 PR) if the account is closed.

# Error log
Adding the following code to `fetchData()`
```javascript
      this.page
      .on('response', response => {
        if (response.status() === 302) {
          console.log(`[response]${response.status()} ${response.url()}\n -> Location:`, response.headers()['location']);
        }
      })
      .on('request', request => {
        if(request.url().includes('balanceAndCreditLimit')) {
          console.log('[request]', `${request.url()}`);
        }
      })
      .on('requestfailed', request => {
        if (request.url().includes('balanceAndCreditLimit')) {
          console.log('[requestfailed]', `${request.failure().errorText} ${request.url()}`);
        }
      });
```

I got this log:
```
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?partyCurrentAccount=[REMOVED]&lang=he
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [response]302 https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
   -> Location: https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [response]302 https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
   -> Location: https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [request] https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  [requestfailed] net::ERR_HTTP2_PROTOCOL_ERROR https://login.bankhapoalim.co.il/ServerServices/current-account/composite/balanceAndCreditLimit?accountId=[REMOVED]&view=details&lang=he
  Error: Evaluation failed: TypeError: Failed to fetch
      at ExecutionContext._evaluateInternal (/workspaces/money/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async ExecutionContext.evaluate (/workspaces/money/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
      at async fetchAccountData (/workspaces/money/node_modules/israeli-bank-scrapers/src/scrapers/hapoalim.ts:154:35)
      at async HapoalimScraper.scrape (/workspaces/money/node_modules/israeli-bank-scrapers/src/scrapers/base-scraper.ts:159:24)
      at async getAccountTransactions (file:///workspaces/money/src/data/scrape.ts:26:20)
      at async scrapeAccount (file:///workspaces/money/src/data/index.ts:64:18)
      at async scrapeAccounts (file:///workspaces/money/src/data/index.ts:27:20)
      at async Promise.all (index 0)
      at async run (file:///workspaces/money/src/index.ts:15:23)
```

**Comment by esakal** [comment]
@daniel-hauser I'll wait to see if anyone comment and will proceed with the merge tomorrow or the day after.
