### ISSUE TITLE
Max scrapper is throwing an error

### ISSUE THREAD

**Issue by felipegrin** [eshaham/israeli-bank-scrapers#814]
Since last week I'm getting this error every time I try to run the Max scrapper through [israeli-ynab-updater](https://github.com/eshaham/israeli-ynab-updater):

```
Max: START_SCRAPING
Max: INITIALIZING
Max: INITIALIZING
(node:90094) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Max: TERMINATING
Max: END_SCRAPING
success: false
error type: GENERIC
error: Navigation timeout of 30000 ms exceeded
Error: Navigation timeout of 30000 ms exceeded
    at scrape (/Users/ephraim/ynab2/israeli-ynab-updater/src/scrape/scrape-base.js:67:11)
    at scrapeIndividual (/Users/ephraim/ynab2/israeli-ynab-updater/src/scrape/scrape-individual.js:118:31)
    at scrapingMainMenu (/Users/ephraim/ynab2/israeli-ynab-updater/src/scrape/scraping-main-menu.js:27:7)
ephraim@MREM01A4276F israeli-ynab-updater % 
```

**Comment by erikash** [comment]
The issue is endless loading for some script or resource on max's website...
I've been a able to workaround this error with a headfull session and clicking stop in the browser window

**Comment by felipegrin** [comment]
> The issue is endless loading for some script or resource on max's website... I've been a able to workaround this error with a headfull session and clicking stop in the browser window

You're right, when I click stop in the browser it works. 
Is there a way to automatically stop the loading of the page? Or to increase the timeout waiting time?

**Comment by liranay** [comment]
I was able to find a messy workaround by editing the following:
lib/scrapers/base-scraper-with-browser.ts
row 179
   `const options = { ...(timeout === null ? null : { timeout }) };`
add `waitUntil: 'domcontentloaded`:
`        const options = { ...(timeout === null ? null : { timeout , waitUntil: 'domcontentloaded'}) };
`

**Comment by daniel-hauser** [comment]
This issue is fixed in #813 (PR is still open).
Patch is available in the [moneyman repo](https://github.com/daniel-hauser/moneyman/blob/796f379f7d6b51354266deb731909339c65bee4d/patches/israeli-bank-scrapers%2B4.0.2%2B001%2Binitial.patch) until the PR will merge
